server:
  port: 2022
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/boom_academy?currentSchema=main
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect