server:
  port: 2022
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/boom_academy?currentSchema=main
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

api:
  info:
    title: Boom acdemy API
    description: This api .....
    version: 1.0
    license-url: nimadir
    license-name: nimadir
    contact-name: boom.uz, boom-academy.uz
    contact-email: boomAcademy@gmail.com
    contact-url: https://boom.uz, https://boom-academy.uz

